FROM mcr.microsoft.com/playwright:v1.56.1-jammy

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY tests ./tests
COPY tsconfig*.json ./
COPY .env.autotest* ./

RUN mkdir -p tests/public/autotest tests/reports tests/storage

ENV NODE_ENV=production
ENV CI=true

CMD ["npm", "run", "test:all"]
