FROM node:20-alpine

WORKDIR /app

# Копируем package files
COPY package*.json ./

# Устанавливаем системные пакеты и зависимости
RUN apk add --no-cache docker-cli docker-cli-compose bash \
  && npm install express cors ws

# Копируем сервер для live-стрима
COPY tests/stream-server ./stream-server

EXPOSE 3002

CMD ["node", "stream-server/index.js"]
