FROM node:20-alpine

WORKDIR /app

# Копируем package files
COPY package*.json ./

# Устанавливаем системные пакеты и зависимости
# Обновляем индекс пакетов и используем правильные имена для Alpine
RUN apk update && \
    apk add --no-cache bash && \
    npm install express cors ws

# Копируем сервер для live-стрима
COPY tests/stream-server ./stream-server

EXPOSE 3002

CMD ["node", "stream-server/index.js"]
